-- DO NOT APPLY THIS FILE'S ORIGINAL VERSION — it has been reviewed and
-- rejected. Kept in the repo (rather than deleted) specifically so the
-- reasoning is visible to whoever finds it next, instead of silently
-- vanishing and possibly getting re-diagnosed and re-proposed later.
--
-- The original version of this file removed the following block from
-- transactions_before_write():
--
--   if NEW.direction = 'Received' and NEW.beekeeper_id is not null and NEW.actor_id is null then
--     NEW.status := 'Approved';
--   end if;
--
-- This block is NOT a bug — it's a deliberate, tested, confirmed business
-- rule from this project's very first Transactions audit: beekeeper-
-- sourced Received transactions have NO approval step at all. ONLY
-- actor-sourced Received transactions (the ones auto-created when another
-- actor hits Send) go through a real Pending -> Approve/Reject workflow.
-- This distinction is the whole reason `direction`, `beekeeper_id`, and
-- `actor_id` all exist as separate fields on this table.
--
-- The test that led to this file's original diagnosis created a
-- transaction for "Musa Ibrahim" — a BEEKEEPER — and then found the
-- Approve/Reject UI unreachable. That's expected and correct: a
-- beekeeper-sourced receipt is SUPPOSED to auto-approve immediately, with
-- no pending state at all. It does not indicate the approval workflow is
-- broken — it indicates the wrong kind of transaction was used to try to
-- exercise it.
--
-- To actually test the real Pending -> Approve/Reject workflow: create a
-- SEND transaction from one actor to a different actor (not a beekeeper
-- receipt). This automatically creates a linked, Pending "Received"
-- record for the destination actor — that linked record is the one that
-- correctly shows the pending banner and Approve/Reject buttons. This is
-- the only way actor-sourced Received transactions currently get created
-- in this system; there's no separate manual "Received from Actor" form.
--
-- Verified live in the database at time of writing: the auto-approve
-- block above is present and unmodified in transactions_before_write() —
-- this file's original version was written but never actually applied,
-- so no live behavior needs reverting. This file exists purely to
-- document why it should stay that way.
